apiVersion: apps/v1
kind: Deployment
metadata:
  name: jmeter-agent
  namespace: jmeter-ns
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jmeter-agent
  template:
    metadata:
      labels:
        app: jmeter-agent
    spec:
      containers:
        - name: jmeter-agent
          image: justb4/jmeter:latest
          command:
            - jmeter
          args:
            - -s
            - -Dserver.rmi.localport=50000
            - -Dserver_port=1099
          ports:
            - containerPort: 1099
            - containerPort: 50000
