apiVersion: v1
kind: Service
metadata:
  name: jmeter-agent
  namespace: jmeter
spec:
  selector:
    app: jmeter-agent
  ports:
    - protocol: TCP
      port: 1099
      targetPort: 1099
  clusterIP: None
