apiVersion: apps/v1
kind: Deployment
metadata:
  name: jmeter-master
  namespace: jmeter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jmeter-master
  template:
    metadata:
      labels:
        app: jmeter-master
    spec:
      containers:
        - name: jmeter-master
          image: justb4/jmeter:latest
          command:
            - jmeter
          args:
            - -n
            - -t /tests/HTTPSignInSignOffPlan.jmx
            - -R jmeter-agent-0.jmeter.svc.cluster.local,jmeter-agent-1.jmeter.svc.cluster.local,jmeter-agent-2.jmeter.svc.cluster.local
            - -l /tests/test-results.jtl
          volumeMounts:
            - name: jmeter-test-files
              mountPath: /tests
      volumes:
        - name: jmeter-test-files
          hostPath:
            path: /path/to/your/test/files
